[build]
# Default build commands. Uncomment to override.
# afl = "AFL_QUIET=1 cargo afl build --features=multifuzz/afl --target-dir=target/afl"
# afl_cmplog = "AFL_QUIET=1 AFL_LLVM_CMPLOG=1 cargo afl build --features=multifuzz/afl --target-dir=target/afl-cmplog"
# honggfuzz = "CARGO_TARGET_DIR=./target/honggfuzz HFUZZ_BUILD_ARGS='--features=multifuzz/honggfuzz' cargo hfuzz build-debug"
# libfuzzer = "CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS='-Cpasses=sancov-module -Cllvm-args=-sanitizer-coverage-level=4 -Cllvm-args=-sanitizer-coverage-trace-compares -Cllvm-args=-sanitizer-coverage-inline-8bit-counters -Cllvm-args=-sanitizer-coverage-pc-table' cargo build --release --target=x86_64-unknown-linux-gnu --features=multifuzz/libfuzzer --target-dir=target/libfuzzer"

[fuzz]
target = "example_crash"
jobs = 3
corpus = "./corpus"
output = "./output/multi"
timeout = 5

[fuzz.afl.all.env]
AFL_AUTORESUME = "1"
AFL_FAST_CAL = "1"
AFL_FORCE_UI = "1"
AFL_IGNORE_UNKNOWN_ENVS = "1"
AFL_IGNORE_SEED_PROBLEMS = "1"
AFL_SKIP_CPUFREQ = "1"
AFL_NO_AFFINITY = "1"

[fuzz.afl.worker0]
args = "-pexplore"

[fuzz.afl.worker0.env]
AFL_FINAL_SYNC = "1"
